
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mf-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/matias-magallanes/apps.git'
    path: 1-mf-apps
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
